server:
  port: 8081
logging:
  level:
    web: debug
spring:
  application:
    name: user-gateway
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
    gateway:
      routes:
      - id: user-middle
        uri: lb://user-middle
        predicates:
        - Path=/user-middle/**
        filters:
        ##- StripPrefix=1